### ISSUE TITLE
missing compiler settings

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#140] opened 2021-09-22 11:34 UTC
CPLC is capable to accept commandline - eg -source 5 -target 8 -release 9 -Xlint and so on.
Settings have to allow this.

**Comment by AurumTheEnd** [comment] 2021-09-24 14:03
Duplicate of #117. Note that the current 1.4 version of CPLC isn't capable of this yet, the feature is only in the works.

**Closed by AurumTheEnd** 2021-09-24 14:03 UTC
